// Banco de palavras usado pelo jogo existente em index.tsx
export const WORDS: { word: string; emoji: string }[] = [
  // animais
  { word: "GATO", emoji: "🐱" },
  { word: "PATO", emoji: "🦆" },
  { word: "MACACO", emoji: "🐵" },
  { word: "PEIXE", emoji: "🐟" },
  { word: "CACHORRO", emoji: "🐶" },
  { word: "COELHO", emoji: "🐰" },
  { word: "LEAO", emoji: "🦁" },
  { word: "TIGRE", emoji: "🐯" },
  { word: "VACA", emoji: "🐮" },
  { word: "PORCO", emoji: "🐷" },
  { word: "GALINHA", emoji: "🐔" },
  { word: "RATO", emoji: "🐭" },
  { word: "URSO", emoji: "🐻" },
  { word: "SAPO", emoji: "🐸" },
  { word: "ABELHA", emoji: "🐝" },
  { word: "BORBOLETA", emoji: "🦋" },
  { word: "ELEFANTE", emoji: "🐘" },
  { word: "GIRAFA", emoji: "🦒" },
  { word: "ZEBRA", emoji: "🦓" },
  { word: "COBRA", emoji: "🐍" },
  { word: "PINGUIM", emoji: "🐧" },
  { word: "CORUJA", emoji: "🦉" },
  { word: "RAPOSA", emoji: "🦊" },
  { word: "LOBO", emoji: "🐺" },
  { word: "CAVALO", emoji: "🐴" },
  { word: "OVELHA", emoji: "🐑" },
  // natureza
  { word: "SOL", emoji: "☀️" },
  { word: "LUA", emoji: "🌙" },
  { word: "FLOR", emoji: "🌻" },
  { word: "ARVORE", emoji: "🌳" },
  { word: "ESTRELA", emoji: "⭐" },
  { word: "NUVEM", emoji: "☁️" },
  { word: "MONTANHA", emoji: "⛰️" },
  { word: "ARCOIRIS", emoji: "🌈" },
  // objetos
  { word: "BOLA", emoji: "⚽" },
  { word: "CASA", emoji: "🏠" },
  { word: "LIVRO", emoji: "📚" },
  { word: "CARRO", emoji: "🚗" },
  { word: "TREM", emoji: "�" },
  { word: "AVIAO", emoji: "✈️" },
  { word: "BARCO", emoji: "⛵" },
  { word: "RELOGIO", emoji: "⏰" },
  { word: "CHAVE", emoji: "�" },
  { word: "BALAO", emoji: "🎈" },
  { word: "CHAPEU", emoji: "🎩" },
  { word: "GUITARRA", emoji: "🎸" },
  { word: "LAPIS", emoji: "✏️" },
  { word: "MOCHILA", emoji: "🎒" },
  // comidas
  { word: "MACA", emoji: "🍎" },
  { word: "BANANA", emoji: "�" },
  { word: "UVA", emoji: "�" },
  { word: "LARANJA", emoji: "�" },
  { word: "MORANGO", emoji: "🍓" },
  { word: "PIZZA", emoji: "�" },
  { word: "BOLO", emoji: "🍰" },
  { word: "PAO", emoji: "🍞" },
  { word: "QUEIJO", emoji: "🧀" },
  { word: "SORVETE", emoji: "🍦" },
];
